-- SELECT DE TODOS OS FILMES COM ANO ANTERIOR A 2000
/*

*/

SELECT *
FROM FILME 
WHERE ANO_FILME <2000
	

-- SELECT DE FILMES ENTRE 2005 E 2010

SELECT *
FROM FILME
WHERE ANO_FILME >=2005 AND ANO_FILME <=2010

SELECT *
FROM FILME
WHERE ANO_FILME BETWEEN 2005 AND 2010


--01 - SELECIONAR TODOS OS DIRETORES

SELECT *
FROM DIRETOR

--02 - SELECIONAR TODOS OS ATORES

SELECT *
FROM FILME_ATOR

--03 - SELECIONAR TODOS OS GENEROS

SELECT *
FROM GENERO

--04 - SELECIONAR TODOS OS FILMES, EXCLUÍDOS, OU NÃO 

SELECT NOME_FILME, DATA_EXCLUSAO_FILME
FROM FILME

--05 - SELECIONAR OS DIRETORES EM ORDEM DE NOME 

SELECT * 
FROM DIRETOR 
ORDER BY NOME_DIRETOR

--06 - SELECIONAR OS ATORES EM ORDEM DE CÓDIGO

SELECT *
FROM ATOR
ORDER BY ID_ATOR 

--07 - SELECIONAR OS GENEROS EM ORDEM DECRESCENTE DO NOME

SELECT *
FROM GENERO
ORDER BY NOME_GENERO DESC

--08 - SELECIONAR O ANO, O NOME ORIGINAL, O NOME EM PORTUGUÊS E O CÓDIGO IMDB DOS FILMES

SELECT ANO_FILME, NOME_ORIGINAL_FILME, NOME_FILME, ID_IMDB_FILME
FROM FILME

--09 - SELECIONAR O NOME ORIGINAL DO FILME, O NOME DO DIRETOR, OS NOMES DOS ATORES E O NOME DOS GÊNEROS

SELECT NOME_ORIGINAL_FILME, NOME_DIRETOR
FROM FILME 
JOIN DIRETOR 
ON FILME.ID_DIRETOR = DIRETOR.ID_DIRETOR

SELECT NOME_ORIGINAL_FILME, NOME_DIRETOR
FROM FILME AS F
JOIN DIRETOR AS D
ON F.ID_DIRETOR = D.ID_DIRETOR

--COMECEI A FAZER DE NOVO AQUI, PARA TREINAR PARA PROVA
-- SELECT DE TODOS OS FILMES COM ANO ANTERIOR A 2000

select NOME_FILME, ANO_FILME
from filme 
where ANO_FILME <2000

-- SELECT DE FILMES ENTRE 2005 E 2010

SELECT *
FROM FILME
WHERE ANO_FILME BETWEEN 2005 AND 2010

--SELECT DE FILMES ONDE CONTEM RAMBO NA COLUNA NOME_ORIGINAL_FILME


SELECT *
FROM FILME 
WHERE NOME_ORIGINAL_FILME LIKE '%RAMBO%'


--01 - SELECIONAR TODOS OS DIRETORES

SELECT *
FROM DIRETOR

--02 - SELECIONAR TODOS OS ATORES

SELECT *
FROM ATOR

--03 - SELECIONAR TODOS OS GENEROS

SELECT *
FROM GENERO

--04 - SELECIONAR TODOS OS FILMES, EXCLUÍDOS, OU NÃO 

SELECT NOME_FILME, DATA_EXCLUSAO_FILME
FROM FILME

--05 - SELECIONAR OS DIRETORES EM ORDEM DE NOME 

SELECT *
FROM DIRETOR
ORDER BY NOME_DIRETOR ASC

--06 - SELECIONAR OS ATORES EM ORDEM DE CÓDIGO

SELECT *
FROM ATOR
ORDER BY ID_ATOR ASC

--07 - SELECIONAR OS GENEROS EM ORDEM DECRESCENTE DO NOME

SELECT *
FROM GENERO 
ORDER BY NOME_GENERO DESC

--08 - SELECIONAR O ANO, O NOME ORIGINAL, O NOME EM PORTUGUÊS E O CÓDIGO IMDB DOS FILMES

SELECT ANO_FILME, NOME_ORIGINAL_FILME, NOME_FILME, ID_IMDB_FILME
FROM FILME 

--09 - SELECIONAR O NOME ORIGINAL DO FILME, O NOME DO DIRETOR, OS NOMES DOS ATORES E O NOME DOS GÊNEROS

SELECT NOME_ORIGINAL_FILME, NOME_DIRETOR, NOME_ATOR, NOME_GENERO
FROM FILME 
JOIN DIRETOR
ON FILME.ID_DIRETOR = DIRETOR.ID_DIRETOR

JOIN FILME_ATOR
ON FILME.ID_FILME = FILME_ATOR.ID_FILME
JOIN ATOR
ON FILME_ATOR.ID_ATOR = ATOR.ID_ATOR

JOIN FILME_GENERO
ON FILME.ID_FILME = FILME_GENERO.ID_FILME
JOIN GENERO
ON FILME_GENERO.ID_GENERO = GENERO.ID_GENERO


--10 - SELECIONAR TODOS OS GÊNEROS COM AS QUANTIDADES DE FILMES DE CADA UM

SELECT GENERO.NOME_GENERO, COUNT(*) as 'Qtde de filmes'
FROM GENERO
JOIN FILME_GENERO
ON GENERO.ID_GENERO = FILME_GENERO.ID_GENERO
GROUP BY NOME_GENERO

---SELECT COM TODOS OS FILMES DOS ANOS 2010,2012 E 2014

SELECT *
FROM FILME
WHERE ANO_FILME IN (2010,2012,2014)

---- SELECIONAR TODOS OS FILMES MAIS ANTIGOS DO ALIEN, OU SEJA, ONDE O ANO É MENOR QUE 2000 E TODOS OS FILMES NOVOS DO HIGHLANDER, OU SEJA, ONDE O ANO É POSTERIOR A 2000

SELECT *
FROM FILME
WHERE NOME_FILME LIKE '%ALIEN%' AND ANO_FILME <2000 OR NOME_FILME LIKE '%HIGHLANDER%'AND ANO_FILME >2000

--11 - SELECIONAR TODOS OS ANOS DOS FILMES, COM AS QUANTIDADES DE FILMES DE CADA UM, ORDENADO DO ANO MAIS RECENTE PARA O MAIS ANTIGO

SELECT ANO_FILME, COUNT(*) AS 'QTDE DE FILMES ANO' 
FROM FILME
GROUP BY ANO_FILME
ORDER BY ANO_FILME DESC

--11,5 - SELECIONAR TODOS OS ANOS DOS FILMES, COM AS QUANTIDADES DE FILMES DE CADA UM, ORDENADO DO ANO MAIS RECENTE PARA O MAIS ANTIGO, POREM RETORNAR APENAS OS ANOS QUE TIVEREM MAIS DE 5 FILMES


SELECT ANO_FILME, COUNT(*) AS 'QTDE DE FILMES ANO' 
FROM FILME
GROUP BY ANO_FILME
HAVING COUNT (*)>5
ORDER BY ANO_FILME DESC

--12 - SELECIONAR TODOS OS FILMES DE ANOS COM MAIS DE 3 FILMES
SELECT ANO_FILME, COUNT(*) AS 'QTDE DE FILMES ANO' 
FROM FILME
GROUP BY ANO_FILME
HAVING COUNT (*)>3

--13 - SELECIONAR TODOS OS DIRETORES QUE FIZERAM MAIS DE UM FILME
SELECT DIRETOR.NOME_DIRETOR, COUNT(*) AS 'QTDE DE FILMES FEITOS'
FROM DIRETOR
JOIN FILME
ON DIRETOR.ID_DIRETOR = FILME.ID_DIRETOR
GROUP BY NOME_DIRETOR
HAVING COUNT(*)>1

--14 - SELECIONAR TODOS OS FILMES EM QUE O PERSONAGEM SINESTRO APARECE (FAZER UTILIZANDO JOIN E SUB QUERY)

SELECT NOME_FILME, FILME_ATOR.NOME_PERSONAGEM
FROM FILME 
JOIN FILME_ATOR
ON FILME.ID_FILME = FILME_ATOR.ID_FILME
WHERE FILME_ATOR.NOME_PERSONAGEM LIKE '%SINESTRO'

--15 - SELECIONAR TODOS OS FILMES EM QUE O ATOR JAMES EARL JONES TRABALHOU, RETORNAR TAMBEM A COLUNA COM O NOME DO ATOR

SELECT FILME.NOME_FILME, ATOR.NOME_ATOR
FROM FILME
JOIN FILME_ATOR 
ON FILME.ID_FILME = FILME_ATOR.ID_FILME
JOIN ATOR
ON FILME_ATOR.ID_ATOR = ATOR.ID_ATOR
WHERE ATOR.NOME_ATOR LIKE 'JAMES EARL JONES'


