CREATE DATABASE TADS

DROP DATABASE TADS

CREATE DATABASE TADS 

/*CHAR VALOR IMUTAVEL O TEXTO (1 CARACTERE) = 4 BYTES 
25 X 4
25 X 4
25 X 4

VARCHAR DADOS DE NOMES QUE ALTERAM (1 CARACTERE) = 8 BYTES

5X8
6X8
8X8
*/
CREATE TABLE TESTE (
ID INTEGER,
NOME VARCHAR(100),
DATA DATE,
VALOR DECIMAL(10,2)
)
/*O 10 SIGNIFICA A QUANTIDADE TOTAL DE CARACTERE (NUMERO) E O 2 E OS DOIS NUMEROS DEPOIS DA VIRGULA.
EXEMPLO: 10.000.000,99
TOTAL DE NUMEROS: 10
TOTAL DEPOIS DA VIRGULA: 2 
*/

DROP TABLE TESTE

CREATE TABLE 

CREATE TABLE TESTE (
ID INTEGER PRIMARY KEY,
NOME VARCHAR(100) NOT NULL,
DATA DATE,
VALOR DECIMAL(10,2)
)