CREATE DATABASE TADS

--DROP DATABASE TADS

--ALTER

CREATE TABLE TESTE
(
  ID INTEGER PRIMARY KEY,
  NOME VARCHAR(100) NOT NULL,
  DATA DATE,
  VALOR DECIMAL(10,2) --(10) TOTAL DE CARÁCTER E (2) NÚMEROS APÓS A VÍRUGLA

)
CREATE TABLE TESTE2
(
  ID INTEGER PRIMARY KEY,
  NOME VARCHAR(100) NOT NULL,
  DATA DATE,
  VALOR DECIMAL(10,2) --(10) TOTAL DE CARÁCTER E (2) NÚMEROS APÓS A VÍRUGLA

)
-- SQL AUTO INCREMENT
-- SQL CHECK
-- SQL DEFAULT
-- SQL FOREIGN KEY



DROP TABLE Persons (
    Personid int IDENTITY(1,1) PRIMARY KEY,
    LastName varchar(255) NOT NULL,
    FirstName varchar(255),
    Age int CHECK (AGE>=18),
	City varchar(255) DEFAULT 'Sandnes'
);

CREATE TABLE Persons (
    Personid int IDENTITY(1,1) PRIMARY KEY,
    LastName varchar(255) NOT NULL,
    FirstName varchar(255),
    Age int CHECK (AGE>=18),
	City varchar(255) DEFAULT 'Sandnes'
);


CREATE TABLE Orders (
    OrderID int NOT NULL PRIMARY KEY,
    OrderNumber int NOT NULL,
    PersonID int FOREIGN KEY REFERENCES Persons(PersonID)
);

--Alteração de tabelas, colunas e exclusão
ALTER TABLE Orders
ADD teste varchar(20)

ALTER TABLE Orders
drop column teste 

ALTER TABLE Orders
Alter column OrderNumber char(2)



CREATE DATABASE TESTE

CREATE TABLE ALUNOS
(
ID_ALUNOS int IDENTITY(1,1) PRIMARY KEY,
NOME_ALUNOS VARCHAR(50),
CELULAR VARCHAR(20),
DATA_NASCIMENTO DATE
);

CREATE TABLE MATERIAS
(
ID_MATERIA int IDENTITY(1,1) PRIMARY KEY,
NOME_MATERIA VARCHAR(20)
)

CREATE TABLE PROVA
(
ID_PROVA int IDENTITY(1,1) PRIMARY KEY,
ID_ALUNO int FOREIGN KEY REFERENCES ALUNOS(ID_ALUNOS),
ID_MATERIA int FOREIGN KEY REFERENCES MATERIAS(ID_MATERIA),
NOTA_P1 INT,
NOTA_P2 int
)

ALTER TABLE PROVA
Alter column NOTA_P1 DECIMAL(4,2)

ALTER TABLE PROVA
Alter column NOTA_P2 DECIMAL(4,2)

ALTER TABLE ALUNOS
Alter column CELULAR VARCHAR(20)

-- sql insert into